In [1]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp

In [2]:
mp_holistic = mp.solutions.holistic # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities

In [3]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = model.process(image)
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    return image, results

In [4]:
def draw_landmarks(image, results):
#     mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION) # Draw face connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS) # Draw pose connections
#     mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw left hand connections
#     mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw right hand connections

In [5]:
def draw_styled_landmarks(image, results):
    # Draw face connections
#     mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION, 
#                              mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
#                              mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
#                              ) 
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
#     # Draw left hand connections
#     mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
#                              mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
#                              mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
#                              ) 
# #     # Draw right hand connections  
#     mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
#                              mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
#                              mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
#                              )

In [6]:
# img = cv2.imread('00000097.jpg', 0)
# plt.imshow(img, cmap='gray')
# type(img)

In [7]:
# with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:

In [8]:
# pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)
# face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)
# lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
# rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)

In [9]:
# if results.face_landmarks: 
#     face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() 
# else: face = np.zeros(1404)
# print(face)

In [10]:
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    return np.concatenate([pose])

In [11]:
# # Path for exported data, numpy arrays
# DATA_PATH = os.path.join('Yoga Pose') 

# # Actions that we try to detect
# actions = np.array(['Grass Hopper'])

# # Thirty videos worth of data
# no_sequences = 5

# # Videos are going to be 30 frames in length
# sequence_length = 5 

# # Folder start
# start_folder = 10

In [12]:
# for action in actions: 
#     for sequence in range(no_sequences):
#         try: 
#             os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
#         except:
#             pass

In [13]:
# # Path for exported data, numpy arrays
# DATA_PATH = os.path.join('Yoga Pose') 

# # Actions that we try to detect
# # actions = np.array(['Cobra','DownDog','Uttanasana'])
# actions = np.array(['Grass Hopper'])
# # Thirty videos worth of data
# no_sequences = 10        # no of folder 

# # Videos are going to be 30 frames in length
# sequence_length = 5  # np file per folder

# # Folder start
# start_folder = 6

# for action in actions: 
#     for sequence in range(no_sequences):
#         try: 
#             os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
#         except:
#             pass
        
# # cap = cv2.VideoCapture(0)

# # for i in range(3):
# #     print(i)
# #     if i == 0:
# #         image_name = '14_0Slomo_Slomo_Trim.mp4'
# #     elif i == 1:
# #         image_name = 'D1.mp4'
# #     elif i == 2:
# #         image_name = 'u1.mp4'
    
# cap = cv2.VideoCapture('Grass Hoppers Arm.mp4')
#     # Set mediapipe model 
# image_list = []
# with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:

#     # NEW LOOP
#     # Loop through actions
#     for action in actions:
#         # Loop through sequences aka videos
#         for sequence in range(no_sequences):
#             # Loop through video length aka sequence length
#             for frame_num in range(sequence_length):
# #                     print(frame_num)
#                 # Read feed
#                 ret, frame = cap.read()

#                 # Make detections
#                 image, results = mediapipe_detection(frame, holistic)
#                 image_list.append(image)
# #                 print(results)
# #                 image_list[frame_num]
#                 # Draw landmarks
#                 draw_styled_landmarks(image, results)

#                 # NEW Apply wait logic
#                 if frame_num == 0: 
# #                     cv2.putText(image_list[frame_num], 'STARTING COLLECTION', (120,200), 
# #                                cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
# #                     cv2.putText(image_list[frame_num], 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
# #                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
#                     # Show to screen
#                     cv2.imshow('OpenCV Feed', image_list[frame_num])
#                     cv2.waitKey(10) #frame per 0.05 sec
#                 else: 
# #                     cv2.putText(image_list[frame_num], 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
# #                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
#                     # Show to screen
#                     cv2.imshow('OpenCV Feed', image_list[frame_num])

#                 # NEW Export keypoints
#                 keypoints = extract_keypoints(results)
#                 npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
#                 np.save(npy_path, keypoints)

#                 # Break gracefully
#                 if cv2.waitKey(10) & 0xFF == ord('q'):
#                     break

#     cap.release()
#     cv2.destroyAllWindows()

In [14]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [15]:
# label_map = {label:num for num, label in enumerate(actions)}

In [16]:
DATA_PATH = os.path.join('Yoga Pose_new0') 
actions = np.array(['Cobra','DownDog','Uttanasana'])
label_map = {label:num for num, label in enumerate(actions)}
sequence_length = 5

sequences, labels = [], []
for action in actions:
    for sequence in np.array(os.listdir(os.path.join(DATA_PATH, action))).astype(int):
        window = []
#         print(sequence)
        for frame_num in range(sequence_length):
#             print(frame_num)
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [17]:
# print(labels, len(sequences))
# sequences[0]         #folder 0

In [18]:
X = np.array(sequences)
y = to_categorical(labels).astype(int)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [21]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [22]:
model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(5,132))) # (30,132)
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(64, return_sequences=False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

In [23]:
print(X_train.shape, X_test.shape)

(36, 5, 132) (9, 5, 132)


In [24]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [25]:
model.fit(X_train, y_train, epochs=500, callbacks=[tb_callback])

Epoch 1/500
2/2 [==============================] - 2s 9ms/step - loss: 1.0979 - categorical_accuracy: 0.3611
Epoch 2/500
2/2 [==============================] - 0s 10ms/step - loss: 1.0920 - categorical_accuracy: 0.6111
Epoch 3/500
2/2 [==============================] - 0s 10ms/step - loss: 1.0868 - categorical_accuracy: 0.6111
Epoch 4/500
2/2 [==============================] - 0s 8ms/step - loss: 1.0826 - categorical_accuracy: 0.5833
Epoch 5/500
2/2 [==============================] - 0s 9ms/step - loss: 1.0794 - categorical_accuracy: 0.5278
Epoch 6/500
2/2 [==============================] - 0s 10ms/step - loss: 1.0721 - categorical_accuracy: 0.5278
Epoch 7/500
2/2 [==============================] - 0s 9ms/step - loss: 1.0631 - categorical_accuracy: 0.5556
Epoch 8/500
2/2 [==============================] - 0s 10ms/step - loss: 1.0424 - categorical_accuracy: 0.6111
Epoch 9/500
2/2 [==============================] - 0s 11ms/step - loss: 1.0117 - categorical_accuracy: 0.6111
Epoch 10/500
2

2/2 [==============================] - 0s 8ms/step - loss: 0.0015 - categorical_accuracy: 1.0000
Epoch 76/500
2/2 [==============================] - 0s 8ms/step - loss: 7.4057e-04 - categorical_accuracy: 1.0000
Epoch 77/500
2/2 [==============================] - 0s 9ms/step - loss: 4.1227e-04 - categorical_accuracy: 1.0000
Epoch 78/500
2/2 [==============================] - 0s 8ms/step - loss: 2.4769e-04 - categorical_accuracy: 1.0000
Epoch 79/500
2/2 [==============================] - 0s 8ms/step - loss: 1.5743e-04 - categorical_accuracy: 1.0000
Epoch 80/500
2/2 [==============================] - 0s 9ms/step - loss: 9.8923e-05 - categorical_accuracy: 1.0000
Epoch 81/500
2/2 [==============================] - 0s 9ms/step - loss: 7.2496e-05 - categorical_accuracy: 1.0000
Epoch 82/500
2/2 [==============================] - 0s 8ms/step - loss: 5.1809e-05 - categorical_accuracy: 1.0000
Epoch 83/500
2/2 [==============================] - 0s 8ms/step - loss: 3.8665e-05 - categorical_accuracy

2/2 [==============================] - 0s 9ms/step - loss: 1.2119e-06 - categorical_accuracy: 1.0000
Epoch 147/500
2/2 [==============================] - 0s 9ms/step - loss: 1.1788e-06 - categorical_accuracy: 1.0000
Epoch 148/500
2/2 [==============================] - 0s 8ms/step - loss: 1.1457e-06 - categorical_accuracy: 1.0000
Epoch 149/500
2/2 [==============================] - 0s 7ms/step - loss: 1.1027e-06 - categorical_accuracy: 1.0000
Epoch 150/500
2/2 [==============================] - 0s 8ms/step - loss: 1.0696e-06 - categorical_accuracy: 1.0000
Epoch 151/500
2/2 [==============================] - 0s 9ms/step - loss: 1.0232e-06 - categorical_accuracy: 1.0000
Epoch 152/500
2/2 [==============================] - 0s 9ms/step - loss: 9.6691e-07 - categorical_accuracy: 1.0000
Epoch 153/500
2/2 [==============================] - 0s 8ms/step - loss: 9.1724e-07 - categorical_accuracy: 1.0000
Epoch 154/500
2/2 [==============================] - 0s 9ms/step - loss: 8.7751e-07 - categori

2/2 [==============================] - 0s 9ms/step - loss: 1.6888e-07 - categorical_accuracy: 1.0000
Epoch 218/500
2/2 [==============================] - 0s 8ms/step - loss: 1.6888e-07 - categorical_accuracy: 1.0000
Epoch 219/500
2/2 [==============================] - 0s 9ms/step - loss: 1.6557e-07 - categorical_accuracy: 1.0000
Epoch 220/500
2/2 [==============================] - 0s 9ms/step - loss: 1.6557e-07 - categorical_accuracy: 1.0000
Epoch 221/500
2/2 [==============================] - 0s 8ms/step - loss: 1.6226e-07 - categorical_accuracy: 1.0000
Epoch 222/500
2/2 [==============================] - 0s 8ms/step - loss: 1.6226e-07 - categorical_accuracy: 1.0000
Epoch 223/500
2/2 [==============================] - 0s 9ms/step - loss: 1.6226e-07 - categorical_accuracy: 1.0000
Epoch 224/500
2/2 [==============================] - 0s 10ms/step - loss: 1.6226e-07 - categorical_accuracy: 1.0000
Epoch 225/500
2/2 [==============================] - 0s 8ms/step - loss: 1.5895e-07 - categor

2/2 [==============================] - 0s 8ms/step - loss: 8.6096e-08 - categorical_accuracy: 1.0000
Epoch 289/500
2/2 [==============================] - 0s 9ms/step - loss: 8.6096e-08 - categorical_accuracy: 1.0000
Epoch 290/500
2/2 [==============================] - 0s 9ms/step - loss: 8.6096e-08 - categorical_accuracy: 1.0000
Epoch 291/500
2/2 [==============================] - 0s 9ms/step - loss: 8.6096e-08 - categorical_accuracy: 1.0000
Epoch 292/500
2/2 [==============================] - 0s 8ms/step - loss: 8.2784e-08 - categorical_accuracy: 1.0000
Epoch 293/500
2/2 [==============================] - 0s 9ms/step - loss: 8.2784e-08 - categorical_accuracy: 1.0000
Epoch 294/500
2/2 [==============================] - 0s 8ms/step - loss: 7.9473e-08 - categorical_accuracy: 1.0000
Epoch 295/500
2/2 [==============================] - 0s 9ms/step - loss: 7.9473e-08 - categorical_accuracy: 1.0000
Epoch 296/500
2/2 [==============================] - 0s 9ms/step - loss: 7.9473e-08 - categori

2/2 [==============================] - 0s 8ms/step - loss: 4.9671e-08 - categorical_accuracy: 1.0000
Epoch 360/500
2/2 [==============================] - 0s 9ms/step - loss: 4.6359e-08 - categorical_accuracy: 1.0000
Epoch 361/500
2/2 [==============================] - 0s 8ms/step - loss: 4.6359e-08 - categorical_accuracy: 1.0000
Epoch 362/500
2/2 [==============================] - 0s 8ms/step - loss: 4.6359e-08 - categorical_accuracy: 1.0000
Epoch 363/500
2/2 [==============================] - 0s 9ms/step - loss: 4.6359e-08 - categorical_accuracy: 1.0000
Epoch 364/500
2/2 [==============================] - 0s 9ms/step - loss: 4.6359e-08 - categorical_accuracy: 1.0000
Epoch 365/500
2/2 [==============================] - 0s 9ms/step - loss: 4.6359e-08 - categorical_accuracy: 1.0000
Epoch 366/500
2/2 [==============================] - 0s 9ms/step - loss: 4.6359e-08 - categorical_accuracy: 1.0000
Epoch 367/500
2/2 [==============================] - 0s 9ms/step - loss: 4.6359e-08 - categori

2/2 [==============================] - 0s 8ms/step - loss: 3.3114e-08 - categorical_accuracy: 1.0000
Epoch 431/500
2/2 [==============================] - 0s 9ms/step - loss: 3.3114e-08 - categorical_accuracy: 1.0000
Epoch 432/500
2/2 [==============================] - 0s 8ms/step - loss: 3.3114e-08 - categorical_accuracy: 1.0000
Epoch 433/500
2/2 [==============================] - 0s 9ms/step - loss: 3.3114e-08 - categorical_accuracy: 1.0000
Epoch 434/500
2/2 [==============================] - 0s 8ms/step - loss: 3.3114e-08 - categorical_accuracy: 1.0000
Epoch 435/500
2/2 [==============================] - 0s 8ms/step - loss: 3.3114e-08 - categorical_accuracy: 1.0000
Epoch 436/500
2/2 [==============================] - 0s 8ms/step - loss: 3.3114e-08 - categorical_accuracy: 1.0000
Epoch 437/500
2/2 [==============================] - 0s 8ms/step - loss: 3.3114e-08 - categorical_accuracy: 1.0000
Epoch 438/500
2/2 [==============================] - 0s 9ms/step - loss: 3.3114e-08 - categori

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 5, 64)             50432     
                                                                 
 lstm_1 (LSTM)               (None, 5, 128)            98816     
                                                                 
 lstm_2 (LSTM)               (None, 64)                49408     
                                                                 
 dense (Dense)               (None, 64)                4160      
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 204,995
Trainable params: 204,995
Non-trai

In [27]:
y_test

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [28]:
actions[np.argmax(y_test[2])]

'DownDog'

In [29]:
model.save('ML_Yoga')

INFO:tensorflow:Assets written to: ML_Yoga\assets


In [30]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score
yhat = model.predict(X_test)

In [31]:
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [32]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[7, 0],
        [1, 1]],

       [[3, 1],
        [0, 5]],

       [[7, 0],
        [0, 2]]], dtype=int64)

In [33]:
accuracy_score(ytrue, yhat)

0.8888888888888888

In [34]:
print(res.shape)
print(res[1])

(132,)
0.5460752844810486


In [35]:
# for num, prob in enumerate(res):
#     print(num, prob)

In [36]:
# %matplotlib inline 
# from matplotlib import pyplot as plt
# plt.imshow(X, interpolation='nearest')
# plt.show()

In [37]:
# colors = [(245,117,16), (117,245,16), (16,117,245)]
colors = (245, 117, 16)
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    print(output_frame.shape)
    print(input_frame.copy())
    print(actions.shape)

    for num, prob in enumerate(res):
#     for i in range(len(actions)):
#         cv2.rectangle(output_frame, (0,60+num*40), (int(prob*100), 90+num*40), colors[num], -1)
#         cv2.rectangle(output_frame, (0,50+num*40), (int(prob*100), 80+num*40), colors, -1)
        cv2.putText(output_frame, actions[num], (20, 20), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255))
        
    return output_frame

In [38]:
# cv2.putText(img, "Hello", (20,20), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0))

In [39]:
# img = cv2.imread('00000097.jpg', 0)
# plt.imshow(img, cmap='gray')
# type(img)

In [40]:
# plt.figure(figsize=(18,18))
# plt.imshow(prob_viz(yhat, actions, image, colors))

In [41]:
sequence = []
sentence = []
predictions = []
threshold = 0.5

cap = cv2.VideoCapture('8_2.mp4')
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
        sequence.append(keypoints)
        sequence = sequence[-30:]
        
        if len(sequence) == 5:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])
            predictions.append(np.argmax(res))
            
            
        #3. Viz logic
            if np.unique(predictions[-10:])[0]==np.argmax(res): 
                if res[np.argmax(res)] > threshold: 
                    
                    if len(sentence) > 0: 
                        if actions[np.argmax(res)] != sentence[-1]:
                            sentence.append(actions[np.argmax(res)])
                    else:
                        sentence.append(actions[np.argmax(res)])

            if len(sentence) > 5: 
                sentence = sentence[-5:]

            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
            
        cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
        cv2.putText(image, ' '.join(sentence), (3,30), 
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
DownDog
(640, 640, 3)
[[[143 167 170]
  [143 167 170]
  [143 167 170]
  ...
  [151 167 174]
  [156 172 179]
  [158 174 181]]

 [[141 165 168]
  [141 165 168]
  [141 165 168]
  ...
  [151 167 174]
  [156 172 179]
  [158 174 181]]

 [[137 161 164]
  [137 161 164]
  [137 161 164]
  ...
  [150 166 173]
  [155 171 178]
  [157 173 180]]

 ...

 [[ 84  70  68]
  [ 88  74  72]
  [ 87  73  71]
  ...
  [ 92  78  71]
  [ 92  78  71]
  [ 92  78  71]]

 [[ 91  77  75]
  [ 90  76  74]
  [ 86  72  70]
  ...
  [ 92  78  71]
  [ 92  78  71]
  [ 92  78  71]]

 [[ 92  78  76]
  [ 88  74  72]
  [ 84  70  68]
  ...
  [ 92  78  71]
  [ 92  78  71]
  [ 92  78  71]]]
(3,)
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

In [42]:
# output_frame = image.copy()
# cv2.putText(output_frame, actions, (0, 85+(2*40)), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)

# plt.figure (figsize=(18,18))
# # plt.imshow(prob_viz(res, actions, image, colors))
# plt.imshow(output_frame)

In [43]:
# image.shape

In [44]:
# X.shape

In [45]:
# colors = (245, 117, 16)
# output_frame = image.copy()
# cv2.rectangle(output_frame, (0,50+1*40), (int(0.5*100), 80+2*40), colors, -1)
# cv2.putText(output_frame, actions[0], (0, 85+(1*40)), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
# plt.figure (figsize=(18,18))
# # plt.imshow(prob_viz(res, actions, image, colors))
# plt.imshow(output_frame)

In [46]:
# # colors = (245, 117, 16)
# plt.figure (figsize=(18,18))
# # for i in range(len(image_list)):
# output_frame = image_list[4].copy()
# # cv2.rectangle(output_frame, (0,50+1*40), (int(0.5*100), 80+2*40), colors, -1)
# # cv2.putText(output_frame, actions[0], (0, 85+(1*40)), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
# plt.imshow(output_frame)

In [47]:

# plt.figure (figsize=(18,18))
# # plt.imshow(prob_viz(res, actions, image, colors))
# plt.imshow(output_frame)

In [48]:
# plt.figure(figsize=(18,18))
# plt.imshow(prob_viz(X, actions, image, colors))